--[[

Lakideus

LEAVE THE STAR... IT BELONGS TO ME...
YOU HAVE PERSISTENCE... BACK OFF NOW...
DO YOU EVER... LISTEN? IT SEEMS TO NOT BE SO...
WELL, NOW YOU'VE MADE ME MAD... BE PREPARED TO FACE MY WRATH!

]]
